/**
 * Generated by `npm run posters`. Do not edit.
 *
 * Clips that have a still beside them, as `<name>.jpg`. See the note in
 * `scripts/posters.mjs` for why this is a list rather than a derived path.
 *
 * Empty until the script is run on a machine with a full ffmpeg — which is
 * the same prerequisite `npm run media` already has. Empty is correct, not
 * broken: it means no shot carries a poster attribute, which is exactly the
 * behaviour the site had before.
 */
export const CLIPS_WITH_POSTER = new Set<string>([]);
